### ISSUE TITLE
Extend max Dart sdk range to `<4.0.0`

### ISSUE THREAD

**Issue by xsahil03x** [syncapod/tart#11]
Hey, Can we extend the maximum Dart SDK range to support all the `Dart 3` versions?

Currently, we support till `3.0.5`, and the current stable latest is `3.0.6`. It's also hard for you to update every time a new SDK version comes.
https://github.com/syncapod/tart/blob/f270fa6725dd078047378e416b6a771f4ca21caf/tart/pubspec.yaml#L6-L7

The solution:
```yaml
environment:
	sdk: ">=2.15.1 <4.0.0"
```

**Comment by xsahil03x** [comment]
@sschwartz96 can you please take a look?

**Comment by sschwartz96** [comment]
Hi @xsahil03x, I will get this fixed over this weekend!

**Comment by xsahil03x** [comment]
Hey @sschwartz96, any update?

**Comment by sschwartz96** [comment]
Closed with #12 

This SDK range will exist with tart v0.5.1
