### ISSUE TITLE
Update http package to ^1.0.0

### ISSUE THREAD

**Issue by d3xvn** [syncapod/tart#9]
Hey 👋 

We are running into an issue because of the version of the http package in tart.
Any chance you can update the version in pubspec to 1.0.0? 

Happy to create a PR if you need it.

Thanks so much.

**Comment by sschwartz96** [comment]
Hi @deven98, this should be fixed and available with [v0.5.0](https://github.com/syncapod/tart/releases/tag/v0.5.0)

[pub.dev/packages/tart](https://pub.dev/packages/tart/versions/0.5.0)

Thank you for letting me know of this outdated package.
